# change prefix to Ctrl + a
unbind C-b 
set -g prefix C-a 
bind C-a send-prefix 
bind -n C-S-Up if -F "#{pane_in_mode}" "send-keys C-S-Up" "copy-mode -e; send-keys C-S-Up"

# reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -g mouse on
set -g focus-events on

# better pane splitting 
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# unbind default ways of splitting
unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"

# vim-style navigation
bind h select-pane -L 
bind j select-pane -D 
bind k select-pane -U 
bind l select-pane -R 

# vim-style pane resizing 
bind -r H resize-pane -L 5 
bind -r J resize-pane -D 5 
bind -r K resize-pane -U 5 
bind -r L resize-pane -R 5 

# don't rename windows 
set-option -g allow-rename off

# clock mode 
# setw -g clock-mode-colour black

# Status bar 
set -g status-position bottom 
set -g status-justify left 
set -g status-style 'fg=black'
set -g status-style 'bg=gray'
set -g status-left ''
set -g status-left-length 50

# pomodoro config
set -g status-right "#{pomodoro_status}"
set -g @pomodoro_toggle 'p'                    # Start/pause a Pomodoro/break
set -g @pomodoro_cancel 'P'                    # Cancel the current session
set -g @pomodoro_skip '_'                      # Skip a Pomodoro/break

set -g @pomodoro_mins 25                       # The duration of the Pomodoro
set -g @pomodoro_break_mins 5                  # The duration of the break after the Pomodoro completes
set -g @pomodoro_intervals 4                   # The number of intervals before a longer break is started
set -g @pomodoro_long_break_mins 25            # The duration of the long break
set -g @pomodoro_repeat 'off'                  # Automatically repeat the Pomodoros?
set -g @pomodoro_disable_breaks 'off'          # Turn off breaks

set -g @pomodoro_on " 🍅"                      # The formatted output when the Pomodoro is running
set -g @pomodoro_complete " ✔︎"                 # The formatted output when the break is running
set -g @pomodoro_pause " ⏸︎"                    # The formatted output when the Pomodoro/break is paused
set -g @pomodoro_prompt_break " ⏲︎ break?"      # The formatted output when waiting to start a break
set -g @pomodoro_prompt_pomodoro " ⏱︎ start?"   # The formatted output when waiting to start a Pomodoro

set -g @pomodoro_menu_position "R"             # The location of the menu relative to the screen
set -g @pomodoro_sound 'off'                   # Sound for desktop notifications (Run `ls /System/Library/Sounds` for a list of sounds to use on Mac)
                                               # (On Linux add `on` to use the `beep` program or add your custom beeping command)
set -g @pomodoro_notifications 'on'           # Enable desktop notifications from your terminal
set -g @pomodoro_granularity 'off'             # Enables MM:SS (ex: 00:10) format instead of the default (ex: 1m)

set -g status-right-style 'fg=black bg=white'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=white'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=black]#F '

setw -g window-status-bell-style 'fg=white bg=black'

# messages
set -g message-style 'fg=white bg=black'
# set -g status-left '#[fg=#B55E84,bold] octavius #[fg=#30363d] | '

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
