-- Generated by nwg-displays on 2026-09-20 at 22:41:15. Do not edit manually.

hl.monitor({
	output = "eDP-1",
	disabled = true,
})
hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "0x0",
	scale = 1,
	vrr = 0,
})
