-- Generated by nwg-displays on 2026-10-03 at 21:16:08. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    cm = "hdr",
    vrr = 0
})
hl.monitor({
    output = "DP-1",
    mode = "1366x768@59.79",
    position = "1920x0",
    scale = 1,
    vrr = 0
})
