-- Generated by nwg-displays on 2026-06-18 at 15:15:19. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1"
})
